### ISSUE TITLE
Non-functional with 17th Jan update

### ISSUE THREAD

**Issue by JacquePott** [SasLuca/RemoveTwitterViewCount#2]
With that update the views count was moved from the leftmost button to rightmost. The extension now removes the comments/reply button and leaves the views visible.

**Comment by SasLuca** [comment]
Yeah, the update was just released today, I will work on a fix and submit it today.

**Comment by SasLuca** [comment]
Fixed it here: https://github.com/SasLuca/RemoveTwitterViewCount/commit/db3c9135900fbf157e9f52345553a988af5c566a

Tested on chrome and firefox and seems to be fine now. I will make a new release and update it on the extension stores.
